### ISSUE TITLE
Promise that never resolves

### ISSUE THREAD

**Issue by sarenjus** [Purple-Unicorns/DynamoDbBackUp#15]
I think I found a bug when you call the library programmatically. I'm utilizing the script to backup a collection of DynamoDB tables. My code creates an array of promises those are returned by Backup.full(). If DynamoDB table contains more than 100 items the backup library (dbInstanceData.js) creates a recursive function calls until all db items are backed up. The recursive function always returns a new promise. However the original promise - first call to the recursive function - never resolves nor rejects and this is an issue in my opinion.

I was wondering why my code execution stops before I get the "final" answer when using Promise.all on my array of promises, but after debugging the code I found out that's the reason. Please check the issue and correct me if I'm wrong.

PS your module is awesome. If I can give an improvement idea please include table name in the console.log messages. Now I can see that there has been various number of items backed up but I can't see which table they belong to.

**Comment by thoean** [comment]
I think #14 is the related bug fix. Can you have a look whether that'd fix your problem?

**Comment by sarenjus** [comment]
Hi

Thanks for your reply. That does the thing. Is there a new version
containing that change in npm?

BR

Jussi

6.12.2016 10.14 "Markus Thurner" <notifications@github.com> kirjoitti:

**Comment by shevchenkos** [comment]
NPM package has been updated to version 0.2.7.
